// <auto-generated />
using Felinoir.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Felinoir.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622203034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Felinoir.Domain.Entities.Cinema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("IT")
                        .HasColumnName("country");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_url");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_cinemas");

                    b.HasIndex("City")
                        .HasDatabaseName("idx_cinemas_city");

                    b.ToTable("cinemas", (string)null);
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.FelixCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CacheName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cache_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expires_at");

                    b.HasKey("Id")
                        .HasName("pk_felix_cache");

                    b.ToTable("felix_cache", (string)null);
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actors")
                        .HasColumnType("text")
                        .HasColumnName("actors");

                    b.Property<string>("ContentRating")
                        .HasColumnType("text")
                        .HasColumnName("content_rating");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Director")
                        .HasColumnType("text")
                        .HasColumnName("director");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Genres")
                        .HasColumnType("text")
                        .HasColumnName("genres");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<string>("ImdbRating")
                        .HasColumnType("text")
                        .HasColumnName("imdb_rating");

                    b.Property<string>("ImdbVotes")
                        .HasColumnType("text")
                        .HasColumnName("imdb_votes");

                    b.Property<string>("MetacriticScore")
                        .HasColumnType("text")
                        .HasColumnName("metacritic_score");

                    b.Property<string>("OmdbEnrichedAt")
                        .HasColumnType("text")
                        .HasColumnName("omdb_enriched_at");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<string>("Rating")
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<string>("Released")
                        .HasColumnType("text")
                        .HasColumnName("released");

                    b.Property<string>("RtRating")
                        .HasColumnType("text")
                        .HasColumnName("rt_rating");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TmdbBackdrops")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_backdrops");

                    b.Property<int?>("TmdbBudget")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_budget");

                    b.Property<string>("TmdbCollection")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_collection");

                    b.Property<string>("TmdbCountry")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_country");

                    b.Property<string>("TmdbEnrichedAt")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_enriched_at");

                    b.Property<string>("TmdbGenre")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_genre");

                    b.Property<string>("TmdbGenreEn")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_genre_en");

                    b.Property<string>("TmdbHomepage")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_homepage");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<string>("TmdbKeywords")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_keywords");

                    b.Property<string>("TmdbLanguage")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_language");

                    b.Property<string>("TmdbOriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_original_title");

                    b.Property<string>("TmdbPlot")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_plot");

                    b.Property<string>("TmdbPlotEn")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_plot_en");

                    b.Property<string>("TmdbPopularity")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_popularity");

                    b.Property<string>("TmdbPosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_poster_url");

                    b.Property<string>("TmdbProductionCompanies")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_production_companies");

                    b.Property<string>("TmdbProductionCountries")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_production_countries");

                    b.Property<string>("TmdbRating")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_rating");

                    b.Property<string>("TmdbRecommendations")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_recommendations");

                    b.Property<int?>("TmdbRevenue")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_revenue");

                    b.Property<string>("TmdbSpokenLanguages")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_spoken_languages");

                    b.Property<string>("TmdbStatus")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_status");

                    b.Property<string>("TmdbTagline")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_tagline");

                    b.Property<string>("TmdbTitle")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_title");

                    b.Property<string>("TmdbTitleEn")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_title_en");

                    b.Property<string>("TmdbTrailerUrlEn")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_trailer_url_en");

                    b.Property<string>("TmdbTrailerUrlIt")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_trailer_url_it");

                    b.Property<string>("TmdbVideos")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_videos");

                    b.Property<string>("TmdbVotes")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_votes");

                    b.Property<string>("TmdbWatchProviders")
                        .HasColumnType("text")
                        .HasColumnName("tmdb_watch_providers");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text")
                        .HasColumnName("trailer_url");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.Property<string>("Writer")
                        .HasColumnType("text")
                        .HasColumnName("writer");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_imdb_id")
                        .HasFilter("imdb_id IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_tmdb_id")
                        .HasFilter("tmdb_id IS NOT NULL");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingUrl")
                        .HasColumnType("text")
                        .HasColumnName("booking_url");

                    b.Property<string>("CinemaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cinema_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Datetime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("datetime");

                    b.Property<string>("Hall")
                        .HasColumnType("text")
                        .HasColumnName("hall");

                    b.Property<bool>("Is3D")
                        .HasColumnType("boolean")
                        .HasColumnName("is_3d");

                    b.Property<bool>("IsOV")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ov");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<string>("SubtitleLanguage")
                        .HasColumnType("text")
                        .HasColumnName("subtitle_language");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_screenings");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_screenings_movie_id");

                    b.HasIndex("CinemaId", "MovieId", "Datetime")
                        .IsUnique()
                        .HasDatabaseName("ix_screenings_cinema_id_movie_id_datetime");

                    b.ToTable("screenings", (string)null);
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.TmdbLookupCache", b =>
                {
                    b.Property<string>("ScrapedTitle")
                        .HasColumnType("text")
                        .HasColumnName("scraped_title");

                    b.Property<string>("ScrapedOriginalTitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("scraped_original_title");

                    b.Property<string>("LookedUpAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("looked_up_at");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("ScrapedTitle", "ScrapedOriginalTitle")
                        .HasName("pk_tmdb_lookup_cache");

                    b.ToTable("tmdb_lookup_cache", (string)null);
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.Screening", b =>
                {
                    b.HasOne("Felinoir.Domain.Entities.Cinema", "Cinema")
                        .WithMany("Screenings")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_cinemas_cinema_id");

                    b.HasOne("Felinoir.Domain.Entities.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_movies_movie_id");

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.Cinema", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("Felinoir.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Screenings");
                });
#pragma warning restore 612, 618
        }
    }
}
